# Site Author
author:
  avatar           : "30098 - Copy - Copy.JPG"
  name             : "Tasnim Jahan"
  pronouns         : "she/her"
  bio              : "Computer Vision & Machine Learning Researcher | Seeking PhD Opportunities"
  location         : "Bangladesh"
  uri              :
  email            :

  arxiv            :
  googlescholar    : "https://scholar.google.com/citations?user=UluH2LsAAAAJ&hl=en"
  impactstory      :
  orcid            : "https://orcid.org/0000-0002-5523-108X"
  semantic         :
  pubmed           :
  researchgate     : "https://www.researchgate.net/profile/Tasnim-Jahan"
  scopus           :

  bitbucket        :
  codepen          :
  dribbble         :
  github           : "Tasnim-Jahan"
  kaggle           :
  stackoverflow    :

  bluesky          :
  facebook         :
  flickr           :
  foursquare       :
  goodreads        :
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         : "tasnim-jahan"
  mastodon         :
  medium           :
  pinterest        :
  soundcloud       :
  steam            :
  telegram         :
  tumblr           :
  twitter          :
  vine             :
  weibo            :
  wikipedia        :
  xing             :
  youtube          :
  zhihu            :
